import "@/di/reflect-metadata";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "./_components/ui/toaster";
import Providers from "./providers";
import { ToastProvider } from "./_components/ui/toast";

const geistSans = localFont({
    src: "./_fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./_fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Invoizio",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased `}
            >
                <Providers>
                    <ToastProvider>
                        <Toaster />
                        {children}
                    </ToastProvider>
                </Providers>
            </body>
        </html>
    );
}
